// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcfryhzcnrulkqeotbyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjZnJ5aHpjbnJ1bGtxZW90Ynl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0Nzc0NTQsImV4cCI6MjA3NDA1MzQ1NH0.0GWqiG1BOA_JmDm7rykpJbFKrk4F16ZCyWCCwjFd4OQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});